export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_ALL_POSTS_REQUEST = "FETCH_ALL_POSTS_REQUEST";
export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_ALL_POSTS_FAILURE = "FETCH_ALL_POSTS_FAILURE";

export const FETCH_MORE_POSTS_REQUEST = "FETCH_MORE_POSTS_REQUEST";
export const FETCH_MORE_POSTS_SUCCESS = "FETCH_MORE_POSTS_SUCCESS";
export const FETCH_MORE_POSTS_FAILURE = "FETCH_MORE_POSTS_FAILURE";

export const FETCH_HOT_POSTS_REQUEST = "FETCH_HOT_POSTS_REQUEST";
export const FETCH_HOT_POSTS_SUCCESS = "FETCH_HOT_POSTS_SUCCESS";
export const FETCH_HOT_POSTS_FAILURE = "FETCH_HOT_POSTS_FAILURE";

export const FETCH_MORE_HOT_POSTS_REQUEST = "FETCH_MORE_HOT_POSTS_REQUEST";
export const FETCH_MORE_HOT_POSTS_SUCCESS = "FETCH_MORE_HOT_POSTS_SUCCESS";
export const FETCH_MORE_HOT_POSTS_FAILURE = "FETCH_MORE_HOT_POSTS_FAILURE";

export const FETCH_REPLIES_REQUEST = "FETCH_REPLIES_REQUEST";
export const FETCH_REPLIES_SUCCESS = "FETCH_REPLIES_SUCCESS";
export const FETCH_REPLIES_FAILURE = "FETCH_REPLIES_FAILURE";

export const FETCH_MORE_REPLIES_REQUEST = "FETCH_MORE_REPLIES_REQUEST";
export const FETCH_MORE_REPLIES_SUCCESS = "FETCH_MORE_REPLIES_SUCCESS";
export const FETCH_MORE_REPLIES_FAILURE = "FETCH_MORE_REPLIES_FAILURE";

export const FETCH_MY_POSTS_REQUEST = "FETCH_MY_POSTS_REQUEST";
export const FETCH_MY_POSTS_SUCCESS = "FETCH_MY_POSTS_SUCCESS";
export const FETCH_MY_POSTS_FAILURE = "FETCH_MY_POSTS_FAILURE";

export const FETCH_MORE_MY_POSTS_REQUEST = "FETCH_MORE_MY_POSTS_REQUEST";
export const FETCH_MORE_MY_POSTS_SUCCESS = "FETCH_MORE_MY_POSTS_SUCCESS";
export const FETCH_MORE_MY_POSTS_FAILURE = "FETCH_MORE_MY_POSTS_FAILURE";

export const FETCH_MY_LIKES_REQUEST = "FETCH_MY_LIKES_REQUEST";
export const FETCH_MY_LIKES_SUCCESS = "FETCH_MY_LIKES_SUCCESS";
export const FETCH_MY_LIKES_FAILURE = "FETCH_MY_LIKES_FAILURE";

export const FETCH_MORE_MY_LIKES_REQUEST = "FETCH_MORE_MY_LIKES_REQUEST";
export const FETCH_MORE_MY_LIKES_SUCCESS = "FETCH_MORE_MY_LIKES_SUCCESS";
export const FETCH_MORE_MY_LIKES_FAILURE = "FETCH_MORE_MY_LIKES_FAILURE";

export const SEND_POST_REQUEST = "SEND_POST_REQUEST";
export const SEND_POST_SUCCESS = "SEND_POST_SUCCESS";
export const SEND_POST_FAILURE = "SEND_POST_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const UNLIKE_POST_REQUEST = "UNLIKE_POST_REQUEST";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAILURE = "UNLIKE_POST_FAILURE";

export const GET_CURRENT_SCREEN = "GET_CURRENT_SCREEN";
export const GET_CURRENT_POST = "GET_CURRENT_POST";
export const GET_CURRENT_HOT_POST = "GET_CURRENT_HOT_POST";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_FAILURE_USERNAME_EXISTS = "SIGNUP_FAILURE_USERNAME_EXISTS";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

// export const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
// export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE";

export const GET_ACCESS_TOKEN_REQUEST = "GET_ACCESS_TOKEN_REQUEST";
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESS";
export const GET_ACCESS_TOKEN_FAILURE = "GET_ACCESS_TOKEN_FAILURE";

export const CHANGE_SEND_TEXT = "CHANGE_SEND_TEXT";
export const POST_SENT_AND_GOT_BACK = "POST_SENT_AND_GOT_BACK";
export const BACK_SCREEN = "BACK_SCREEN";
export const NAVIGATE = "NAVIGATE";
export const ADD_TO_REPLIES = "ADD_TO_REPLIES";
export const TOGGLE_ANONYMOUS = "TOGGLE_ANONYMOUS";
